site_name: Honeydew
theme:
  name: "material"
  features:
    - content.code.copy
    - content.code.select    

plugins:
  - search
  - mkdocstrings
  - autorefs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - Honeydew Docs: index.md
  - MySQL Connector: mysql.md
  - GCP Connector: gcp.md
  - GCP BigQuery Connector: gcp-bigquery.md
  - GCP Cloud Logging Connector: gcp-logging.md
  - GCP Secret Manager Connector: gcp-secretmanager.md
  - GCP Cloud Storage Connector: gcp-storage.md
  - GCP Translate Connector: gcp-translate.md
  - SSH Connector: ssh.md
  - Utility Functions: utils.md
  - Notification Functions: notification.md
  - How-To Guides: how-to-guides.md
